
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: function/
            # Properties needed for dev (actually set when setting up all services)
            Handler: responder.entry
            Runtime: python3.9
            Events:
                ApiEvent:
                    Type: HttpApi
            Environment:
                Variables:
                    # These must be defined else SAM won't set them (actual values in .dev_env.json)
                    stello_env: ''
                    stello_version: ''
                    stello_msgs_bucket: ''
                    stello_topic_arn: ''
                    stello_region: ''
                    stello_rollbar_responder: ''
