
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
    Function:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: function/
            # Properties needed for dev (actually set when setting up all services)
            Handler: responder.entry
            Runtime: python3.9
            Events:
                ApiEvent:
                    Type: HttpApi
