
codename: stello
domain: stello.news  # For marketing purposes (use self.document.domain for technical matters)
name: Stello
short_name: Stello
description: A new way to send newsletters that are secure & interactive
author:
    name: Gracious Tech
    email: support@gracious.tech
    post: https://h2imjyrdl2.execute-api.us-west-2.amazonaws.com/
