
codename: stello
domain: stello.news  # For marketing purposes (use self.document.domain for technical matters)
name: Stello
short_name: Stello
# WARN description can't contain '&' etc when building for appx
description: A new way to send newsletters that are secure and interactive
author:
    name: Gracious Tech
    email: support@gracious.tech
