// Module of svgs imported as strings
// NOTE ?raw-svg triggers custom Vite plugin that uses SVGO and still imports as a string
// NOTE Dynamic importing not desirable as involves importing every single icon, even the unused


// Custom images
export * as logo                    from '@/branding/logo.svg?raw-svg'
export * as gt_logo                 from '@/branding/gt_logo.svg?raw-svg'
export * as decor_compose           from '@/assets/decor/draft.svg?raw-svg'


// Custom icons
export * as icon_google             from '@/assets/icons/google.svg?raw-svg'
export * as icon_microsoft          from '@/assets/icons/microsoft.svg?raw-svg'
export * as icon_mailchimp          from '@/assets/icons/mailchimp.svg?raw-svg'
export * as icon_next_plan          from '@/assets/icons/next_plan.svg?raw-svg'
export * as icon_import             from '@/assets/icons/import.svg?raw-svg'
export * as icon_post_add           from '@/assets/icons/post_add.svg?raw-svg'
export * as icon_video              from '@/assets/icons/video.svg?raw-svg'
export * as icon_checkbox_cross     from '@/assets/icons/checkbox_cross.svg?raw-svg'
export * as icon_privacy_tip        from '@/assets/icons/privacy_tip.svg?raw-svg'
export * as icon_groups             from '@/assets/icons/groups.svg?raw-svg'
export * as icon_section_merge      from '@/assets/icons/section_merge.svg?raw-svg'
export * as icon_section_separate   from '@/assets/icons/section_separate.svg?raw-svg'
export * as icon_mark_chat_read     from '@/assets/icons/mark_chat_read.svg?raw-svg'
export * as icon_tag                from '@/assets/icons/tag.svg?raw-svg'
export * as icon_highlight          from '@/assets/icons/highlight.svg?raw-svg'
export * as icon_heading            from '@/assets/icons/heading.svg?raw-svg'
export * as icon_subheading         from '@/assets/icons/subheading.svg?raw-svg'
export * as icon_checkbox_null      from '@/assets/icons/checkbox_null.svg?raw-svg'
export * as icon_auto_awesome       from '@/assets/icons/auto_awesome.svg?raw-svg'
export * as icon_face_retouching_off from '@/assets/icons/face_retouching_off.svg?raw-svg'
export * as icon_content_paste      from '@/assets/icons/content_paste.svg?raw-svg'  // New version

// Material icons
export * as icon_brightness_4       from 'md-icon-svgs/brightness_4.svg?raw-svg'
export * as icon_chat_bubble_outline from 'md-icon-svgs/chat_bubble_outline.svg?raw-svg'
export * as icon_thumb_up           from 'md-icon-svgs/thumb_up.svg?raw-svg'
export * as icon_reply              from 'md-icon-svgs/reply.svg?raw-svg'
export * as icon_clear              from 'md-icon-svgs/clear.svg?raw-svg'
export * as icon_unfold_more        from 'md-icon-svgs/unfold_more.svg?raw-svg'
export * as icon_unfold_less        from 'md-icon-svgs/unfold_less.svg?raw-svg'
export * as icon_archive            from 'md-icon-svgs/archive.svg?raw-svg'
export * as icon_swap_horiz         from 'md-icon-svgs/swap_horiz.svg?raw-svg'
export * as icon_expand_more        from 'md-icon-svgs/expand_more.svg?raw-svg'
export * as icon_compare_arrows     from 'md-icon-svgs/compare_arrows.svg?raw-svg'
export * as icon_cloud_download     from 'md-icon-svgs/cloud_download.svg?raw-svg'
export * as icon_settings           from 'md-icon-svgs/settings.svg?raw-svg'
export * as icon_arrow_back         from 'md-icon-svgs/arrow_back.svg?raw-svg'
export * as icon_arrow_forward      from 'md-icon-svgs/arrow_forward.svg?raw-svg'
export * as icon_arrow_upward       from 'md-icon-svgs/arrow_upward.svg?raw-svg'
export * as icon_arrow_downward     from 'md-icon-svgs/arrow_downward.svg?raw-svg'
export * as icon_arrow_drop_down    from 'md-icon-svgs/arrow_drop_down.svg?raw-svg'
export * as icon_more_vert          from 'md-icon-svgs/more_vert.svg?raw-svg'
export * as icon_chevron_left       from 'md-icon-svgs/chevron_left.svg?raw-svg'
export * as icon_chevron_right      from 'md-icon-svgs/chevron_right.svg?raw-svg'
export * as icon_open_in_new        from 'md-icon-svgs/open_in_new.svg?raw-svg'
export * as icon_view_list          from 'md-icon-svgs/view_list.svg?raw-svg'
export * as icon_subject            from 'md-icon-svgs/subject.svg?raw-svg'
export * as icon_group              from 'md-icon-svgs/group.svg?raw-svg'
export * as icon_attach_money       from 'md-icon-svgs/attach_money.svg?raw-svg'
export * as icon_get_app            from 'md-icon-svgs/get_app.svg?raw-svg'
export * as icon_warning            from 'md-icon-svgs/warning.svg?raw-svg'
export * as icon_info               from 'md-icon-svgs/info.svg?raw-svg'
export * as icon_close              from 'md-icon-svgs/close.svg?raw-svg'
export * as icon_share              from 'md-icon-svgs/share.svg?raw-svg'
export * as icon_hearing            from 'md-icon-svgs/hearing.svg?raw-svg'
export * as icon_record_voice_over  from 'md-icon-svgs/record_voice_over.svg?raw-svg'
export * as icon_network_check      from 'md-icon-svgs/network_check.svg?raw-svg'
export * as icon_star               from 'md-icon-svgs/star.svg?raw-svg'
export * as icon_star_border        from 'md-icon-svgs/star_border.svg?raw-svg'
export * as icon_schedule           from 'md-icon-svgs/schedule.svg?raw-svg'
export * as icon_chat               from 'md-icon-svgs/chat.svg?raw-svg'
export * as icon_help               from 'md-icon-svgs/help.svg?raw-svg'
export * as icon_mail               from 'md-icon-svgs/mail.svg?raw-svg'
export * as icon_play_arrow         from 'md-icon-svgs/play_arrow.svg?raw-svg'
export * as icon_pause              from 'md-icon-svgs/pause.svg?raw-svg'
export * as icon_skip_next          from 'md-icon-svgs/skip_next.svg?raw-svg'
export * as icon_error              from 'md-icon-svgs/error.svg?raw-svg'
export * as icon_keyboard_tab       from 'md-icon-svgs/keyboard_tab.svg?raw-svg'
export * as icon_meeting_room       from 'md-icon-svgs/meeting_room.svg?raw-svg'
export * as icon_volume_off         from 'md-icon-svgs/volume_off.svg?raw-svg'
export * as icon_volume_up          from 'md-icon-svgs/volume_up.svg?raw-svg'
export * as icon_volume_down        from 'md-icon-svgs/volume_down.svg?raw-svg'
export * as icon_subscriptions      from 'md-icon-svgs/subscriptions.svg?raw-svg'
export * as icon_send               from 'md-icon-svgs/send.svg?raw-svg'
export * as icon_done               from 'md-icon-svgs/done.svg?raw-svg'
export * as icon_delete             from 'md-icon-svgs/delete.svg?raw-svg'
export * as icon_edit               from 'md-icon-svgs/edit.svg?raw-svg'
export * as icon_live_tv            from 'md-icon-svgs/live_tv.svg?raw-svg'
export * as icon_fullscreen         from 'md-icon-svgs/fullscreen.svg?raw-svg'
export * as icon_lock               from 'md-icon-svgs/lock.svg?raw-svg'
export * as icon_palette            from 'md-icon-svgs/palette.svg?raw-svg'
export * as icon_add                from 'md-icon-svgs/add.svg?raw-svg'
export * as icon_remove             from 'md-icon-svgs/remove.svg?raw-svg'
export * as icon_checkbox_true      from 'md-icon-svgs/check_box.svg?raw-svg'
export * as icon_checkbox_false     from 'md-icon-svgs/check_box_outline_blank.svg?raw-svg'
export * as icon_security           from 'md-icon-svgs/security.svg?raw-svg'
export * as icon_image              from 'md-icon-svgs/image.svg?raw-svg'
export * as icon_library_books      from 'md-icon-svgs/library_books.svg?raw-svg'
export * as icon_fingerprint        from 'md-icon-svgs/fingerprint.svg?raw-svg'
export * as icon_contact_mail       from 'md-icon-svgs/contact_mail.svg?raw-svg'
export * as icon_attach_file        from 'md-icon-svgs/attach_file.svg?raw-svg'
export * as icon_pie_chart          from 'md-icon-svgs/pie_chart.svg?raw-svg'
export * as icon_format_bold        from 'md-icon-svgs/format_bold.svg?raw-svg'
export * as icon_format_italic      from 'md-icon-svgs/format_italic.svg?raw-svg'
export * as icon_link               from 'md-icon-svgs/link.svg?raw-svg'
export * as icon_title              from 'md-icon-svgs/title.svg?raw-svg'
export * as icon_text_fields        from 'md-icon-svgs/text_fields.svg?raw-svg'
export * as icon_list_numbered      from 'md-icon-svgs/format_list_numbered.svg?raw-svg'
export * as icon_list_bulleted      from 'md-icon-svgs/format_list_bulleted.svg?raw-svg'
export * as icon_radio_checked      from 'md-icon-svgs/radio_button_checked.svg?raw-svg'
export * as icon_radio_unchecked    from 'md-icon-svgs/radio_button_unchecked.svg?raw-svg'
export * as icon_format_quote       from 'md-icon-svgs/format_quote.svg?raw-svg'
export * as icon_visibility         from 'md-icon-svgs/visibility.svg?raw-svg'
export * as icon_visibility_off     from 'md-icon-svgs/visibility_off.svg?raw-svg'
export * as icon_cancel             from 'md-icon-svgs/cancel.svg?raw-svg'
export * as icon_check_circle       from 'md-icon-svgs/check_circle.svg?raw-svg'
export * as icon_sync               from 'md-icon-svgs/sync.svg?raw-svg'
export * as icon_money              from 'md-icon-svgs/monetization_on.svg?raw-svg'
export * as icon_short_text         from 'md-icon-svgs/short_text.svg?raw-svg'
export * as icon_crop               from 'md-icon-svgs/crop.svg?raw-svg'
export * as icon_rotate_right       from 'md-icon-svgs/rotate_right.svg?raw-svg'
export * as icon_undo               from 'md-icon-svgs/undo.svg?raw-svg'
export * as icon_content_cut        from 'md-icon-svgs/content_cut.svg?raw-svg'
