#!/bin/bash
# Apply project config throughout all components
set -e
cd "$(dirname "$(dirname "$0")")"


# Apply app config to all components
node app_config/apply.ts

# electron/package.json relies on app_config but is static, so must also be updated
node electron/update_package_json.ts
