#!/bin/bash
# Type check everything
# WARN vue-tsc requires @vue/runtime-dom (provided by Vue3 but needed in top level node_modules)
# WARN Keep this list in sync with .eslintrc.js
# WARN NO set -e (failure is manually tracked)
cd "$(dirname "$(dirname "$0")")"


# Track exit code since bash usually only sets to last command's
EXIT_CODE=0


if [[ "$1" == "" || "$1" == "." ]]; then
    node_modules/.bin/tsc --project . || EXIT_CODE=1
fi


if [[ "$1" == "" || "$1" == "app" ]]; then
    # NOTE Need to force tsc to show colors when piped
    node_modules/.bin/vue-tsc --project app/src --pretty | node_modules/.bin/ts-node .bin/audit_types_filter.ts || EXIT_CODE=1
fi


if [[ "$1" == "" || "$1" == "displayer" ]]; then
    node_modules/.bin/vue-tsc --project displayer/src || EXIT_CODE=1
fi


# Ensure indicate failure if any errors (not just if last errored)
exit $EXIT_CODE
