#!/bin/bash
# Run tests for electron
set -e
cd "$(dirname "$(dirname "$0")")"


cd electron/tests
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    # Use xvfb to run headless (a requirement for CI)
    xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- ../../node_modules/.bin/playwright "${@:-test}"
else
    ../../node_modules/.bin/playwright "${@:-test}"
fi
