#!/bin/bash
# Lint entire project
set -e
cd "$(dirname "$(dirname "$0")")"


# NOTE Avoid linting shared dir twice (lint via displayer since typings work better with Vue 3)
# NOTE ironically the TS plugin has trouble parsing .eslintrc.js!
node_modules/.bin/eslint --ext .js,.ts,.vue --ignore-path=.gitignore --ignore-pattern="app/src/shared/**/*" --ignore-pattern=".eslintrc.js" "$@" .
