#!/bin/bash
# Lint entire project
set -e
cd "$(dirname "$(dirname "$0")")"


# NOTE Uses a lot of memory so need to increase node's default
# NOTE Ignores and file extensions now configured in eslint.config.mjs
NODE_OPTIONS="--max-old-space-size=4096" node_modules/.bin/eslint "${@:-.}"
