#!/bin/bash
# Run tests for electron
set -e
cd "$(dirname "$(dirname "$0")")"


cd electron/tests
xvfb-run --auto-servernum --server-args="-screen 0 1280x960x24" -- ../../node_modules/.bin/playwright "${@:-test}"
