#!/bin/bash
# Run tests for electron in debug mode (unpackaged electron + dev app server)
set -e
cd "$(dirname "$(dirname "$0")")"


# Build electron source before running tests
.bin/build_electron

cd electron/tests
PWDEBUG=1 ../../node_modules/.bin/playwright "${@:-test}"
