#!/bin/bash

# Type check all components


cd `dirname "$0"`
cd ..


# If an arg given, just check that component
if [[ "$1" ]]; then
    node_modules/.bin/vue-tsc --project "$1"
    exit
fi


EXIT_CODE=0

# WARN Keep this list in sync with .eslintrc.js
# WARN vue-tsc requires @vue/runtime-dom (provided by Vue3 but needed in top level node_modules)
node_modules/.bin/tsc --project app || EXIT_CODE=1
node_modules/.bin/vue-tsc --project app/src || EXIT_CODE=1
node_modules/.bin/tsc --project app_config || EXIT_CODE=1
node_modules/.bin/tsc --project displayer || EXIT_CODE=1
node_modules/.bin/vue-tsc --project displayer/src || EXIT_CODE=1
node_modules/.bin/tsc --project electron || EXIT_CODE=1
# TODO responder

# Ensure indicate failure if any errors (not just if last errored)
exit $EXIT_CODE
