#!/bin/bash
# Run full audit of project
set -ex
cd "$(dirname "$(dirname "$0")")"


echo -n "Do you want to do a fresh build before testing? [Y/n] "
read fresh_build
if [[ "$fresh_build" != "n" ]]; then
    .bin/setup_dev
    .bin/build_responder_aws
    .bin/build_displayer
    .bin/build_app
    .bin/build_electron
    .bin/build_electron_package
fi


.bin/audit_lint_errors  # TODO include warnings when ready
.bin/audit_types
.bin/audit_test
.bin/audit_e2e_displayer
.bin/audit_e2e_electron
