#!/bin/bash
# Build lambda functions
set -e
cd "$(dirname "$(dirname "$0")")"

cd host

# Build ts to js
rm -rf accounts/dist  # WARN careful!
accounts/node_modules/.bin/esbuild accounts/src/*.ts --platform=node --format=cjs --sourcemap --outdir=accounts/dist

# Build functions using SAM
# NOTE SAM is smart enough to not rebuild functions that use same code
sam build --config-file template_input.toml

# Remove hidden files (contain dev credentials)
find .aws-sam/build -type f -name ".dev_env*" -delete

# Grant permission to everyone, or lambda won't be able to execute
chmod -R a+rwx .aws-sam/build
