#!/bin/bash

set -e
cd "$(dirname "$(dirname "$0")")"

# Load reactions
.bin/reactions


# Install packages
cd displayer
npm ci
cd ..
cd app
npm ci
cd ..


# Build
.bin/build_displayer
# .bin/build_responder_aws (currently doing this locally and committing due to complexity)
.bin/build_app
