#!/bin/bash

# Since Vite can't yet do transforms on the base index.html, it is done manually before vite runs
# TODO Add postcss etc if needed

cd `dirname "$0"`
OPTIONS_JS=`realpath build_displayer_index_options.js`
cd ../displayer
PATH="`realpath node_modules/.bin`:$PATH"


# Don't compress/minify/etc if in dev mode
MODE_ARGS_CSS="--style=compressed"
MODE_ARGS_JS="--minify"
MODE_ARGS_HTML=""
if [ "$1" == "dev" ]; then
    MODE_ARGS_CSS=""
    MODE_ARGS_JS=""
    MODE_ARGS_HTML="--pretty"
fi


export CSS=`sass $MODE_ARGS_CSS index/index.sass`
export JS=`esbuild --bundle $MODE_ARGS_JS index/index.ts`
pug --obj=$OPTIONS_JS $MODE_ARGS_HTML --out=. index/index.pug
