#!/bin/bash
set -e


# Clear the dist dir
# WARN cd executed inline to ensure cannot rm wrong dir
cd `dirname "$0"` && cd ../electron && rm -r dist


# Copy src to dist
cp --archive src dist


# Write config file to dist from env
echo "{\"rollbar_electron\": \"$ROLLBAR_ELECTRON\"}" > dist/config.json


# Build main and preload scripts
./node_modules/.bin/esbuild dist/main.ts dist/preload.ts --platform=node --format=cjs --sourcemap --outdir=dist


# Rm typescript files
find dist -name "*.ts" -type f,l -delete
