#!/bin/bash
# Build electron source (doesn't package)
set -e
cd "$(dirname "$(dirname "$0")")"


# Clear the dist dir
rm -rf electron/dist  # WARN careful!


# Copy src to dist
cd electron
cp --archive src dist


# Write config file to dist from env
echo "{\"rollbar_electron\": \"$ROLLBAR_ELECTRON\"}" > dist/config.json


# Build main and preload scripts
./node_modules/.bin/esbuild dist/main.ts dist/preload.ts --platform=node --format=cjs --sourcemap --outdir=dist


# Rm typescript files
find dist -name "*.ts" -type f,l -delete
