#!/bin/bash
# Package built electron app for current OS
set -e
cd "$(dirname "$(dirname "$0")")"


# Determine platform args
# NOTE $OSTYPE is a bash builtin var (not specific to CI and not provided manually)
PLATFORM_ARGS='--windows appx'
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    PLATFORM_ARGS='--linux AppImage'
elif [[ "$OSTYPE" == "linux-gnu" ]]; then
    # Electron Updater still relies on zip for updates, even if dmg used to install
    PLATFORM_ARGS='--mac dmg zip'
fi


# Package electron app for platform
cd electron
./node_modules/.bin/electron-builder $PLATFORM_ARGS "$@"
