#!/bin/bash
# Package built electron app for current OS
set -e
cd "$(dirname "$(dirname "$0")")"


# Determine platform args
# NOTE $OSTYPE is a bash builtin var (not specific to CI and not provided manually)
# WARN $OSTYPE for mac often has a version attached, like "darwin19", so use mac as the default
echo "$OSTYPE"
PLATFORM_ARGS='--mac dmg zip'  # Electron Updater still relies on zip for updates for dmg install
if [[ "$OSTYPE" == "linux-gnu" ]]; then
    PLATFORM_ARGS='--linux AppImage'
elif [[ "$OSTYPE" == "msys" ]]; then
    PLATFORM_ARGS='--windows appx'
    # CI will have this var set for code signing on mac, but it will also trigger signing on windows
    # So must unset, as Windows store handles signing, so it isn't required for appx
    unset CSC_LINK
fi


# Package electron app for platform
cd electron
./node_modules/.bin/electron-builder $PLATFORM_ARGS "$@"
