#!/bin/bash
# Build displayer and place tarball of result in app
set -e
cd "$(dirname "$(dirname "$0")")"


# Build
cd displayer
./node_modules/.bin/vite build --assetsDir 'displayer'

# Fix issue with vite dynamic import (https://github.com/vitejs/vite/discussions/4319)
# Give dynamic import of lottie a root-relative path instead of a script-relative path
# NOTE This issue only occurs randomly in some browsers and is hard to reproduce
sed --in-place 's/\.\/lottie_light/\/displayer\/lottie_light/' dist/displayer/index.*.js

# Tar index and assets and place in app
# WARN Be sure to avoid including a dev dir in the tar
# WARN `assets` dir is reserved for message assets, so displayer assets put in `displayer` dir
cd dist
tar --create --file ../../app/static/displayer.tar index.html displayer
