#!/bin/bash
# Deploy displayer for hosted storage (takes env arg -- dev|prod)
set -e
cd "$(dirname "$(dirname "$0")")"

# Note deploy env
env=${1:-dev}
echo "Deploying displayer to $env environment"

# Load in env vars for deployment
source deploy_host_${env}.env
read -s -p "AWS_SECRET_ACCESS_KEY: "
export AWS_SECRET_ACCESS_KEY="$REPLY"
echo  # Password input doesn't look like it worked otherwise (as silenced)
echo "Uploading..."

# Add proprietary reactions
read -s -p "REACTIONS_PASSWORD: "
REACTIONS_PASSWORD="$REPLY" .bin/reactions
echo

# Do fresh build of displayer
.bin/build_displayer

# Upload assets
cd displayer/dist_compressed
aws s3 sync --content-encoding gzip --delete . "s3://$STELLO_HOSTED_BUCKET"

# Invalidate cloudfront
aws cloudfront create-invalidation --distribution-id "$STELLO_HOSTED_CF" --paths '/*'
