#!/bin/bash
# Deploy AWS services for hosted storage (dev)
set -e
cd "$(dirname "$(dirname "$0")")"

cd host
../node_modules/.bin/ts-node template_builder.ts
../.bin/build_host
sam deploy --config-file template_input.toml

# SetPrincipalTagAttributeMap not supported by CloudFormation yet
# TODO Waiting on https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/779
echo "MANUAL: Enable attributes for access control mapping 'username' -> 'cognito:username'"
