#!/bin/bash
# Deploy displayer for hosted storage (takes env arg -- dev|prod)
set -e
cd "$(dirname "$(dirname "$0")")"

# Note deploy env
env=${1:-dev}
echo "Deploying displayer to $env environment"

# Load in env vars for deployment
source deploy_host_${env}.env
read -s -p "AWS_SECRET_ACCESS_KEY: "
export AWS_SECRET_ACCESS_KEY="$REPLY"
echo  # Password input doesn't look like it worked otherwise (as silenced)
echo "Uploading..."

# Do fresh build of displayer
.bin/build_displayer

# Backup previously uploaded version in case something goes wrong
# NOTE These files are gzip compressed
cd displayer/dist_compressed
aws s3 sync --delete "s3://$STELLO_HOSTED_BUCKET" ../dist_prev/

# Upload assets
aws s3 sync --content-encoding gzip --delete . "s3://$STELLO_HOSTED_BUCKET"

# Invalidate cloudfront
aws cloudfront create-invalidation --distribution-id "$STELLO_HOSTED_CF" --paths '/*'
