#!/bin/bash
# Deploy AWS services for hosted storage (dev)
set -e
cd "$(dirname "$(dirname "$0")")"

cd host
../node_modules/.bin/ts-node template_builder.ts
../.bin/build_host_accounts
../.bin/build_host_responder
sam deploy --config-file template_input.toml
