#!/bin/bash

cd `dirname "$0"`
cd ..

# NOTE Performance will be bad if run on development build (test on production instead)
app/node_modules/.bin/lighthouse --no-enable-error-reporting --quiet --output json --chrome-flags="--no-sandbox --headless" http://localhost:8080 "$@"
