#!/bin/bash
# Create new release for app (updates version throughout project) if audit succeeds
set -e
cd "$(dirname "$(dirname "$0")")"


audit_lint_errors
audit_types
audit_test_electron
audit_test_displayer

pipenv run python .bin/release.py
