#!/bin/bash
# Move proposed CI artifacts into production
set -e
cd "$(dirname "$(dirname "$0")")"


# Confirm have deployed host if needed
echo -n "Have you run deploy_host or deploy_host_displayer (if needed)? [y/N] "
read have_deployed
if [[ "$have_deployed" != "y" ]]; then
    echo "Aborted"
    exit
fi


# Config
BUCKET="stello-releases"
CF_DIST="E3BA5K555JRNHM"


# Prompt for credentials
read -p "AWS_ACCESS_KEY_ID: "
export AWS_ACCESS_KEY_ID="$REPLY"
read -s -p "AWS_SECRET_ACCESS_KEY: "
export AWS_SECRET_ACCESS_KEY="$REPLY"
echo  # Password input doesn't look like it worked otherwise (as silenced)
echo "Publishing..."


# Move proposed assets into official dir, overwriting existing
aws s3 cp --recursive s3://${BUCKET}/electron_proposed/ s3://${BUCKET}/electron/


# Invalidate all in cloudfront so caching doesn't delay access to new assets
aws cloudfront create-invalidation --distribution-id "${CF_DIST}" --paths "/*"


# Must manually publish for Windows
echo "IMPORTANT: Now manually publish using Windows store too"
echo "https://stello-releases.s3-us-west-2.amazonaws.com/electron/stello.appx"
