#!/bin/bash
# Create new release for app (updates version throughout project) if audit succeeds
set -e
cd "$(dirname "$(dirname "$0")")"

echo -n "Run audit first? [Y/n] "
read run_audit

if [[ "$run_audit" != "n" ]]; then
    .bin/audit
fi

pipenv run python .bin/release.py
