#!/bin/bash
# Serve displayer in dev mode
set -e
cd "$(dirname "$(dirname "$0")")"


PORT=8002
cd displayer

echo
echo "http://localhost:$PORT/#`cat public/dev/hash.txt`"
echo

./node_modules/.bin/vite --port $PORT
