#!/bin/bash
# Build and run unpackaged electron
set -e
cd "$(dirname "$(dirname "$0")")"


.bin/build_electron
cd electron
# NOTE --disable-gpu set just to silence some warnings
node_modules/.bin/electron --disable-gpu .
