#!/bin/bash
# Build and run unpackaged electron
set -e
cd "$(dirname "$(dirname "$0")")"


.bin/build_electron
cd electron
# TODO re-enable security warnings once done: https://github.com/electron/electron/issues/30880
# NOTE --disable-gpu set just to silence some warnings
ELECTRON_DISABLE_SECURITY_WARNINGS=true node_modules/.bin/electron --disable-gpu .
