#!/bin/bash
# Setup project for development (should be re-run safe)
set -e
cd "$(dirname "$(dirname "$0")")"


# Install packages
pipenv sync
.bin/all_node npm ci


# TODO Create dev configs (see .gitignore)
