#!/bin/bash
# Setup project for development
set -e
cd "$(dirname "$(dirname "$0")")"


# Install packages
pipenv install
npm ci
cd app
npm ci
cd ../app_config
npm ci
cd ../displayer
npm ci
cd ../electron
npm ci
cd ..


# Load reactions
.bin/reactions


# TODO Create dev configs (see .gitignore)
