#!/bin/bash
# Update all dependencies without introducing breaking changes
set -e
cd "$(dirname "$(dirname "$0")")"


# TODO pipenv setup needs to changing to allow this (currently all are version "*")
all_node npm update
