#!/bin/bash
# Update all dependencies to latest versions (may include breaking changes)
set -e
cd "$(dirname "$(dirname "$0")")"


pipenv update  # Since all deps have version "*" they upgrade to latest possible
path_to_ncu="$PWD/node_modules/.bin/ncu"
.bin/all_node "$path_to_ncu" -u
.bin/all_node rm package-lock.json  # Easiest way to ensure nested deps also updated
.bin/all_node npm install
