
name: test

on: push

defaults:
    run:
        shell: bash  # Windows doesn't default to bash

jobs:

    build_app_base:
        name: Build app base so tests can use it
        runs-on: ubuntu-latest
        steps:

            -   name: Checkout same commit from same repository as this Github Action is from
                uses: actions/checkout@v2

            -   name: Install and cache latest compatible version of node
                uses: actions/setup-node@v2
                with:
                    node-version: '14'
                    cache: 'npm'
                    cache-dependency-path: '**/package-lock.json'

            -   name: Install root node modules
                run: npm ci

            -   name: Install node modules for app
                working-directory: ./app
                run: npm ci

            -   name: Install node modules for displayer
                working-directory: ./displayer
                run: npm ci

            -   name: Build the generic base of the app
                run: |
                    .bin/reactions
                    .bin/build_displayer
                    # .bin/build_responder_aws (done locally and committed due to complexity)
                    .bin/build_app
                env:
                    VITE_OAUTH_SECRET_GOOGLE: ${{ secrets.OAUTH_SECRET_GOOGLE }}
                    VITE_ROLLBAR_APP: ${{ secrets.ROLLBAR_APP }}
                    VITE_ROLLBAR_RESPONDER: ${{ secrets.ROLLBAR_RESPONDER }}
                    VITE_ROLLBAR_DISPLAYER: ${{ secrets.ROLLBAR_DISPLAYER }}
                    REACTIONS_PASSWORD: ${{ secrets.REACTIONS_PASSWORD }}

            -   name: Save app base for other jobs to use
                uses: actions/upload-artifact@v2
                with:
                    name: app_base
                    path: app/dist


    test_electron:
        name: Package the app with Electron and test
        needs: build_app_base
        strategy:
            fail-fast: false
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
        runs-on: ${{ matrix.os }}
        steps:

            -   name: Checkout same commit from same repository as this Github Action is from
                uses: actions/checkout@v2

            -   name: Install and cache latest compatible version of node
                uses: actions/setup-node@v2
                with:
                    node-version: '14'
                    cache: 'npm'
                    cache-dependency-path: '**/package-lock.json'

            -   name: Install root node modules
                run: |
                    npm ci
                    npx playwright install --with-deps chromium
                env:
                    PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD: 1

            -   name: Install node modules for Electron
                working-directory: ./electron
                run: npm ci

            -   name: Build electron source code
                run: .bin/build_electron
                env:
                    ROLLBAR_ELECTRON: ${{ secrets.ROLLBAR_ELECTRON }}

            -   name: Get app base from previous job
                uses: actions/download-artifact@v2
                with:
                    name: app_base
                    path: electron/dist/app

            -   name: Package
                run: .bin/build_electron_package --publish=never

            -   name: Test
                run: .bin/audit_test_electron
